In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,VotingClassifier

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [2]:
data=pd.read_csv("/home/harsh/Downloads/data.csv")
x=data.iloc[:,2:-1]
y=data.iloc[:,1]

In [3]:
#preprocess categorical variable
lblEncoder=LabelEncoder()
y=lblEncoder.fit_transform(y)

In [4]:
#no missing data
x.isnull().values.any()

False

In [5]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2019,test_size=0.2)

In [6]:
#Feature Scaling
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
pca=PCA(n_components=None)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)
explained_var=pca.explained_variance_ratio_
explained_var*100

array([4.58461666e+01, 1.81336894e+01, 9.35157333e+00, 6.50407783e+00,
       5.32104207e+00, 3.85626924e+00, 2.19173194e+00, 1.59650897e+00,
       1.36561027e+00, 1.21141577e+00, 1.02597792e+00, 8.43374463e-01,
       6.00404645e-01, 5.44194895e-01, 3.32961659e-01, 2.60070292e-01,
       2.02965650e-01, 1.57138580e-01, 1.42954220e-01, 1.10982354e-01,
       9.49540313e-02, 8.24951909e-02, 6.83459970e-02, 6.24002393e-02,
       3.64565028e-02, 2.53139364e-02, 2.30737509e-02, 4.85226628e-03,
       2.57127474e-03, 4.26659974e-04])

In [8]:
#so we r taking 5 pca components as they explians 85% of variance
pca=PCA(n_components=5)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)

In [9]:
#implementing logisic regression
lr=LogisticRegression(random_state=2019)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuraccy score:",accuracy_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred))

[[70  1]
 [ 1 42]]
Accuraccy score: 98.24561403508771
F1 score: 0.9767441860465116


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [10]:
svc=SVC(kernel='linear',random_state=2019)
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuraccy score:",accuracy_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred))

[[70  1]
 [ 1 42]]
Accuraccy score: 98.24561403508771
F1 score: 0.9767441860465116


In [11]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuraccy score:",accuracy_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred))

[[68  3]
 [ 4 39]]
Accuraccy score: 93.85964912280701
F1 score: 0.9176470588235294


In [12]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuraccy score:",accuracy_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred))

[[68  3]
 [ 3 40]]
Accuraccy score: 94.73684210526315
F1 score: 0.9302325581395349


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [14]:
max_vote=VotingClassifier(estimators=[('logisic_regression',lr),('support_vector_classifier',svc),('naive_bayes',gnb),('random_forest',rf)])
max_vote.fit(x_train,y_train)
y_pred=max_vote.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuraccy score:",accuracy_score(y_test,y_pred)*100)
print("F1 score:",f1_score(y_test,y_pred))

[[71  0]
 [ 2 41]]
Accuraccy score: 98.24561403508771
F1 score: 0.9761904761904763


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
